# Site settings
title: 2CMO-666-1516 website
email: philippe.depauw@arteveldehs.be
description: "2CMO-666-1516 website for the mass. We want the share all or knowledge on webtechnologies with you all :)" 
keywords: "HTML5, CSS3, JavaScript, jQuery, Responsive, Grid"
author: "2CMO-666-1516 | Bachelor of Graphic and Digital Media | Artevelde University College Ghent"
copyright: "Copyright 2010-16 Artevelde University College Ghent. All Rights Reserved."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://2CMO-666-1516.github.io" # the base hostname & protocol for your site
twitter_username: drdynscript
github_username:  phildp99

# Build settings
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed  
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
exclude:
  - gulpfile
  - node_modules/
  - src/
  - Gemfile
  - LICENSE
  - package.json
  - README.md